# Generated by Django 5.2.9 on 2026-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('publisher', models.CharField(max_length=150, verbose_name='Издательство')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
